### ISSUE TITLE
//load lua blockmouse error?

### ISSUE THREAD

**Issue by Friendpie** [johan-sorman/windower-blockmouse#1]
I’m trying to get your add on to work, but I’m clearly not doing something right. I placed the “blockmouse” folder in my Winder4 Addons folder.

In game I typed //load lua blockmouse but I get an error in the console saying “lua does not exist.” 

I can’t seem to get it to autoload either. Do I need to use plugin_manager add on to get it to work?

edit: it works with plugin_manager! I’ll leave this up for anyone having problems in the future.

**Comment by johan-sorman** [comment]
Hi, Sorry for delayed reply. I'm glad you figured it out. You need to load it in console. Typing "lua load blockmouse" in your init file will autoload it.
